export const US_GAAP_ACCOUNTS = [
  // ASSETS
  { code: '1000', name: 'ASSETS',                          type: 'ASSET',     subtype: 'Header',              normalBalance: 'DEBIT',  isSystem: true },
  { code: '1010', name: 'Cash',                            type: 'ASSET',     subtype: 'Current Asset',       normalBalance: 'DEBIT',  isSystem: true },
  { code: '1020', name: 'Accounts Receivable',             type: 'ASSET',     subtype: 'Current Asset',       normalBalance: 'DEBIT',  isSystem: true },
  { code: '1030', name: 'Inventory',                       type: 'ASSET',     subtype: 'Current Asset',       normalBalance: 'DEBIT',  isSystem: true },
  { code: '1040', name: 'Prepaid Expenses',                type: 'ASSET',     subtype: 'Current Asset',       normalBalance: 'DEBIT',  isSystem: true },
  { code: '1050', name: 'Other Current Assets',            type: 'ASSET',     subtype: 'Current Asset',       normalBalance: 'DEBIT',  isSystem: false },
  { code: '1500', name: 'Fixed Assets',                    type: 'ASSET',     subtype: 'Fixed Asset',         normalBalance: 'DEBIT',  isSystem: true },
  { code: '1510', name: 'Equipment',                       type: 'ASSET',     subtype: 'Fixed Asset',         normalBalance: 'DEBIT',  isSystem: false },
  { code: '1520', name: 'Accum. Depreciation - Equipment', type: 'ASSET',     subtype: 'Contra Asset',        normalBalance: 'CREDIT', isSystem: false },
  { code: '1900', name: 'Other Assets',                    type: 'ASSET',     subtype: 'Other Asset',         normalBalance: 'DEBIT',  isSystem: false },
  // LIABILITIES
  { code: '2000', name: 'LIABILITIES',                     type: 'LIABILITY', subtype: 'Header',              normalBalance: 'CREDIT', isSystem: true },
  { code: '2010', name: 'Accounts Payable',                type: 'LIABILITY', subtype: 'Current Liability',   normalBalance: 'CREDIT', isSystem: true },
  { code: '2020', name: 'Sales Tax Payable',               type: 'LIABILITY', subtype: 'Current Liability',   normalBalance: 'CREDIT', isSystem: true },
  { code: '2030', name: 'Accrued Expenses',                type: 'LIABILITY', subtype: 'Current Liability',   normalBalance: 'CREDIT', isSystem: false },
  { code: '2040', name: 'Payroll Liabilities',             type: 'LIABILITY', subtype: 'Current Liability',   normalBalance: 'CREDIT', isSystem: false },
  { code: '2100', name: 'Long-term Debt',                  type: 'LIABILITY', subtype: 'Long-term Liability', normalBalance: 'CREDIT', isSystem: false },
  // EQUITY
  { code: '3000', name: 'EQUITY',                          type: 'EQUITY',    subtype: 'Header',              normalBalance: 'CREDIT', isSystem: true },
  { code: '3010', name: "Owner's Capital",                 type: 'EQUITY',    subtype: 'Capital',             normalBalance: 'CREDIT', isSystem: true },
  { code: '3020', name: 'Retained Earnings',               type: 'EQUITY',    subtype: 'Retained Earnings',   normalBalance: 'CREDIT', isSystem: true },
  { code: '3030', name: "Owner's Drawings",                type: 'EQUITY',    subtype: 'Drawings',            normalBalance: 'DEBIT',  isSystem: false },
  // REVENUE
  { code: '4000', name: 'REVENUE',                         type: 'REVENUE',   subtype: 'Header',              normalBalance: 'CREDIT', isSystem: true },
  { code: '4010', name: 'Sales Revenue',                   type: 'REVENUE',   subtype: 'Operating Revenue',   normalBalance: 'CREDIT', isSystem: true },
  { code: '4020', name: 'Service Revenue',                 type: 'REVENUE',   subtype: 'Operating Revenue',   normalBalance: 'CREDIT', isSystem: false },
  { code: '4030', name: 'Rental Income',                   type: 'REVENUE',   subtype: 'Operating Revenue',   normalBalance: 'CREDIT', isSystem: false },
  { code: '4900', name: 'Other Income',                    type: 'REVENUE',   subtype: 'Non-Operating',       normalBalance: 'CREDIT', isSystem: false },
  // EXPENSES
  { code: '5000', name: 'EXPENSES',                        type: 'EXPENSE',   subtype: 'Header',              normalBalance: 'DEBIT',  isSystem: true },
  { code: '5010', name: 'Cost of Goods Sold',              type: 'EXPENSE',   subtype: 'COGS',                normalBalance: 'DEBIT',  isSystem: true },
  { code: '5100', name: 'Salaries & Wages',                type: 'EXPENSE',   subtype: 'Operating Expense',   normalBalance: 'DEBIT',  isSystem: false },
  { code: '5110', name: 'Rent Expense',                    type: 'EXPENSE',   subtype: 'Operating Expense',   normalBalance: 'DEBIT',  isSystem: false },
  { code: '5120', name: 'Utilities Expense',               type: 'EXPENSE',   subtype: 'Operating Expense',   normalBalance: 'DEBIT',  isSystem: false },
  { code: '5130', name: 'Depreciation Expense',            type: 'EXPENSE',   subtype: 'Operating Expense',   normalBalance: 'DEBIT',  isSystem: false },
  { code: '5140', name: 'Insurance Expense',               type: 'EXPENSE',   subtype: 'Operating Expense',   normalBalance: 'DEBIT',  isSystem: false },
  { code: '5150', name: 'Office Supplies',                 type: 'EXPENSE',   subtype: 'Operating Expense',   normalBalance: 'DEBIT',  isSystem: false },
  { code: '5160', name: 'Advertising & Marketing',         type: 'EXPENSE',   subtype: 'Operating Expense',   normalBalance: 'DEBIT',  isSystem: false },
  { code: '5170', name: 'Travel & Auto',                   type: 'EXPENSE',   subtype: 'Operating Expense',   normalBalance: 'DEBIT',  isSystem: false },
  { code: '5180', name: 'Meals & Entertainment',           type: 'EXPENSE',   subtype: 'Operating Expense',   normalBalance: 'DEBIT',  isSystem: false },
  { code: '5190', name: 'Professional Fees',               type: 'EXPENSE',   subtype: 'Operating Expense',   normalBalance: 'DEBIT',  isSystem: false },
  { code: '5200', name: 'Bank Fees & Charges',             type: 'EXPENSE',   subtype: 'Operating Expense',   normalBalance: 'DEBIT',  isSystem: false },
  { code: '5900', name: 'Other Expenses',                  type: 'EXPENSE',   subtype: 'Non-Operating',       normalBalance: 'DEBIT',  isSystem: false },
];
